import { defineConfig } from "orval";

export default defineConfig({
  agentServer: {
    input: {
      target: "./openapi.json",
    },
    output: {
      mode: "single",
      target: "./src/api/generated/agent-server.ts",
      schemas: false,
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      override: {
        fetch: {
          includeHttpResponseReturnType: false,
        },
        mutator: {
          path: "./src/api/orval-mutator.ts",
          name: "apiMutator",
        },
        query: {
          signal: true,
        },
        header: (info) => [
          "Generated by Orval from the agent-server OpenAPI document.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
        ],
      },
    },
  },
});
