kind: pipeline
type: docker
name: nova-model-gateway-client

trigger:
  branch:
    - master

volumes:
  - name: pnpm-cache
    host:
      path: /var/lib/drone-cache/pnpm/nova-model-gateway-client

steps:
  - name: restore-pnpm-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: pnpm-cache
        path: /cache
    settings:
      restore: true
      mount:
        - /cache/pnpm-store

  - name: build and package
    image: node:20-alpine
    volumes:
      - name: pnpm-cache
        path: /cache
    commands:
      - APP_NAME=model-gateway-client
      - APP_DIR=apps/$APP_NAME
      - corepack enable
      - corepack prepare pnpm@9 --activate
      - pnpm config set store-dir /cache/pnpm-store
      - pnpm config set registry https://registry.npmmirror.com/
      - pnpm -w install --no-frozen-lockfile --filter "$APP_NAME..."
      - cd $APP_DIR
      - pnpm run build
      - tar -czf /drone/src/$APP_NAME.tar.gz ./dist

  - name: rebuild-pnpm-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: pnpm-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /cache/pnpm-store

  - name: scp
    image: appleboy/drone-scp
    settings:
      debug: false
      source:
        - model-gateway-client.tar.gz
      host:
        from_secret: CURRENT_HOST
      username: root
      port: 22
      password:
        from_secret: SSH_PWD
      target: /temp/app/

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: CURRENT_HOST
      username: root
      password:
        from_secret: SSH_PWD
      port: 22
      command_timeout: 2m
      script:
        - APP_NAME=model-gateway-client
        - APP_DIR=/data/app/$APP_NAME
        - rm -rf $APP_DIR
        - mkdir -p $APP_DIR
        - tar xzf /temp/app/$APP_NAME.tar.gz -C $APP_DIR
        - rm -f /temp/app/$APP_NAME.tar.gz
        - ls -al $APP_DIR
