import { defineConfig } from "orval";

export default defineConfig({
  modelConfig: {
    input: { target: "./openapi.json" },
    output: {
      mode: "single",
      target: "./src/api/generated/model-config.ts",
      schemas: false,
      client: "react-query",
      httpClient: "fetch",
      clean: true,
      override: {
        fetch: { includeHttpResponseReturnType: false },
        mutator: { path: "./src/api/orval-mutator.ts", name: "apiMutator" },
        query: { signal: true },
        header: (info) => [
          "Generated by Orval from the model-config admin OpenAPI document.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
        ],
      },
    },
  },
});
